module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	golang.org/x/mod v0.4.0 // indirect
	golang.org/x/tools v0.0.0-20201211185031-d93e913c1a58 // indirect
	honnef.co/go/tools v0.0.1-2020.1.6 // cmd/staticcheck
)
